import MainHeader from "@/components/main-header/main-header.js";
import "./globals.css";
import Head from "next/head";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <script src="https://cdn.babylonjs.com/babylon.js"></script>
      </Head>
      <body>
        <MainHeader />
        {children}
      </body>
    </html>
  );
}
